version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: todo_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://admin:admin%40123@mongo:27017/todo_db?authSource=admin"
      MONGO_DB: todo_db
      MONGO_COLLECTION: tasks
    depends_on:
      - mongo

volumes:
  mongo_data:
